### PR TITLE
Added a sorting option

### PR DESCRIPTION
**Pull request by chamini2**
That way we can see kind of similar colors together.

### CODE REVIEW

**Comment by chamini2** [comment]
Fixed some stuff, hope it's fine for you. Now we can sort by clicking in the column `Color name` or in the column `Hex Triplets`, and below the `Hex Triplets` title I added an `R G B`, clicking each enables sorting only by the value of `R`, `G`, or `B`, respectively.

**Comment by chamini2** [comment]
One problem, though, is that sometimes the `RGB` value doesn't match the _LaTeX_ percentage, and we're using the _LaTeX_ percentage to actually sort the `RGB` value.

**Comment by doolin** [comment]
No worries about what the sort is on. Someone else can add other types of sorting later, if they're so inclined.

**Comment by doolin** [comment]
Deployed.

Thanks for your interest. Color sorting is actually a really hard problem, and this is a good start.

**Comment by chamini2** [comment]
Awesome! Glad to help.

**Pull request merged**
