### PR TITLE
New: Package instead of input

### PR DESCRIPTION
**Pull request by foreachthing**
* Removed `makeInclFile.py` and replace it with `make_tex_package.py` (new: it generates a package (`LatexColors.incl.sty`) now.)
* Overview of all colors (like website) with RGB, CMYK, HSV and HSL color information (use pdflatex or similar, to render the pdf -` LatexColors.incl.sty` required).

### CODE REVIEW

**Comment by doolin** [comment]
Would like to have a Pipfile and Pipfile.lock with this: https://github.com/pypa/pipfile

Apologies for the lag, busy at work.

**Comment by foreachthing** [comment]
I am sorry, but that's where I stop.
I don't have much interest in learning pipfile.
If you don't want to merge, just close it. If at all, I'll continue to update my fork at https://github.com/foreachthing/latexcolor.com.

**Comment by doolin** [comment]
Ok, I'll take it, as this is a volunteer project.

Very strongly suggest learning Pipfile system. It's mandatory where I work, and given its officially supported status, I suspect it will become much more prevalent in the Python community.

**Comment by foreachthing** [comment]
I am no pro - I just did this for the fun trying python ;-)
Thanks for the merge and the suggestion to use pylint and pipfile.

**Pull request merged**
