### PR TITLE
Include-File to be used in TeX

### PR DESCRIPTION
**Pull request by foreachthing**
Make Include-File from `colors.txt` to be used in TeX directly.

### CODE REVIEW

**Comment by doolin** [comment]
First, thanks!

I''m super busy at the moment, will need to carve a few hours out to look at this. It will be a good time to do some updating and upgrading as well, which is overdue.

**Comment by doolin** [comment]
Haven't forgotten, work is crazy busy at the moment.

**Comment by foreachthing** [comment]
don't worry about it!

**Comment by foreachthing** [comment]
Made some changes!
Now, it's to be used as a package `\usepackage{LatexColors.incl}` and then you can use `\tcolor{airforceblue}`. I changed the command to `\tcolor{}` so one can use the `cwl` file with TexStudio. You don't have to use `\tcolor{}` and `\color{}` will still work.

**Comment by foreachthing** [comment]
Made some changes!
Now, it's to be used as a package `\usepackage{LatexColors.incl}` and then you can use `\tcolor{airforceblue}`. I changed the command to `\tcolor{}` so one can use the `cwl` file with TexStudio. You don't have to use `\tcolor{}` and `\color{}` will still work.

**Comment by doolin** [comment]
Looking at this now.

It would be helpful if you could squash into a single commit.

**Comment by foreachthing** [comment]
I don't know how to do that ... can't you just cherry pick or merge?
I tried to PR again but the commits remain.

**Comment by foreachthing** [comment]
go here: https://github.com/Inventium/latexcolor.com/pull/6

**Comment by doolin** [comment]
cool, will check it when I get off the train

**Pull request closed without merging**
